### PR TITLE
fix: font_family

### PR DESCRIPTION
**Pull request by bevsxyz**
Comic Sans MS is not suitable for SVG files on the web. Hence using cursive instead is better for the web.

Another option is to supply multiple font families as suggested here https://stackoverflow.com/a/21335048
This would require allowing the text function to take font_family as a string or a list based on context.

### CODE REVIEW

**Comment by bevsxyz** [comment]
The below figure is with `font_family='Comic Sans MS'`
chalkboard

The below figure is with `font_family='cursive'`
chalkboard-cursive

**Comment by spakin** [comment]
> Another option is to supply multiple font families as suggested here https://stackoverflow.com/a/21335048
> This would require allowing the text function to take font_family as a string or a list based on context.

I prefer this option, supplying multiple font families.  Could you please update your pull request to specify `font_family='"Comic Sans MS", cursive'`.  (At some point in the future I might allow `font_family` to accept a list, but this will suffice for now.)

**Comment by bevsxyz** [comment]
@spakin Sorry had been busy with my thesis. I didn't know the single-quote trick for escaping double-quotes. I have committed the changes.

**Comment by spakin** [comment]
Thanks for the pull request, and good luck with your thesis.

**Comment by spakin** [comment]
For the record, 46604f5e72686eb852af03c537399c8eb84ecca7 adds the ability to provide `font_family` either a string (`font_family='"Comic Sans MS", cursive'`) or a list of strings (`font_family=['Comic Sans MS', 'cursive']`).

**Pull request merged**
